server:
  port: 8082
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service-group
      key-serializar: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
customer-service:
  base-url: http://localhost:8081/api/customers
springdoc:
  api-docs:
    enable: true
    paht: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
  endpoint:
    health:
      show-details: always
