server:
 port: 8083
spring:
 application:
   name: credit-service
 data:
   mongodb:
     uri: mongodb://localhost:27017/bankdb
   redis:
     host: localhost
     port: 6379
customer-service:
 base-url: http://localhost:8081/api/customers
springdoc:
 api-docs:
   enabled: true
   path: /v3/api-docs
 swagger-ui:
   path: /swagger-ui.html
   operationsSorter: method
   tagsSorter: alpha
   docExpansion: none
management:
 endpoints:
   web:
     exposure:
       include: health, info, metrics, env
 endpoint:
   health:
     show-details: always
