server:
    port: 80
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server-cxgjf0gxbhbsfccz.canadacentral-01.azurewebsites.net/eureka
    instance:
        hostname: creditservice-drf5cjfnfvhcemfk.canadacentral-01.azurewebsites.net
        nonSecurePort: 80
        securePort: 443
        securePortEnabled: true
        nonSecurePortEnabled: false
        preferIpAddress: false
        instanceId: ${spring.application.name}:${random.uuid}
        statusPageUrl: https://${eureka.instance.hostname}/actuator/info
        healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
        homePageUrl: https://${eureka.instance.hostname}/
spring:
    application:
        name: credit-service
    data:
        mongodb:
            uri: mongodb+srv://jeremy:Hola1234@bank-db.mongocluster.cosmos.azure.com/bank-db?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
        redis:
            host: redis-bootcamp.redis.cache.windows.net
            port: 6380
            password: ySxGplL2IJg6maslG3CUqZFemQjgkJOxkAzCaMBUle0=
            ssl: true
            timeout: 10000
    kafka:
        bootstrap-servers: bankkafka.servicebus.windows.net:9093
        properties:
            security:
                protocol: SASL_SSL
            sasl:
                mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="\$\ConnectionString" password="Endpoint=sb://bankkafka.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tVQTP6WHDJNy08SKfHu1t9qrz486rolhD+AEhJM5Ohk=";
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: credit:com.bank.creditservice.model.credit.Credit, creditcard:com.bank.creditservice.model.creditcard.CreditCard
                spring.json.trusted.packages: "*"
customer-service:
    base-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api/customers
account-service:
    base-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api/accounts
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
        tagsSorter: alpha
        docExpansion: none
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, env
    endpoint:
        health:
            show-details: always
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 10s
                permittedNumberOfCallsInHalfOpenState: 3
                slowCallDurationThreshold: 5s
                slowCallRateThreshold: 50
            instances:
                customerService:
                    baseConfig: default
                    timeoutDuration: 2s
                accountService:
                    baseConfig: default
                    timeoutDuration: 2s
