server:
  port: 8081
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializar: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
