server:
  port: 8085
spring:
  application:
    name: report-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
  endpoint:
    health:
      show-details: always
services:
  account:
    url: http://localhost:8082
  credit:
    url: http://localhost:8083
  transaction:
    url: http://localhost:8084
    
