server:
    port: 80
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server-cxgjf0gxbhbsfccz.canadacentral-01.azurewebsites.net/eureka
    instance:
        hostname: report-service-dwc7ewehckdfe2er.canadacentral-01.azurewebsites.net
        nonSecurePort: 80
        securePort: 443
        securePortEnabled: true
        nonSecurePortEnabled: false
        preferIpAddress: false
        instanceId: ${spring.application.name}:${random.uuid}
        statusPageUrl: https://${eureka.instance.hostname}/actuator/info
        healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
        homePageUrl: https://${eureka.instance.hostname}/ 
spring:
    application:
        name: report-service
    data:
        mongodb:
            uri: mongodb+srv://jeremy:Hola1234@bank-db.mongocluster.cosmos.azure.com/bank-db?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
        tagsSorter: alpha
        docExpansion: none
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, env
    endpoint:
        health:
            show-details: always
services:
    account-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api
    credit-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api
    transaction-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api
    customer-url: https://apigateway-awfrh3a7gweucpbb.canadacentral-01.azurewebsites.net/api/customers
logging:
    level:
        org.springframework.data.mongodb.core: DEBUG
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 10s
                permittedNumberOfCallsInHalfOpenState: 3
                slowCallDurationThreshold: 5s
                slowCallRateThreshold: 50
            instances:
                customerService:
                    baseConfig: default
                    timeoutDuration: 2s
                accountService:
                    baseConfig: default
                    timeoutDuration: 2s
                creditService:
                    baseConfig: default
                    timeoutDuration: 2s
                debitCardService:
                    baseConfig: default
                    timeoutDuration: 2s
