server:
 port: 8084
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761
spring:
 application:
   name: transaction-service
 data:
   mongodb:
     uri: mongodb://localhost:27017/bankdb
   redis:
     host: localhost
     port: 6379
 kafka:
   bootstrap-servers: NTTD-3KDMY64:9092
   consumer:
     group-id: transaction-service-group
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     auto-offset-reset: latest
     properties:
      spring.json.type.mapping: account:com.bank.transactionservice.model.Account,credit:com.bank.transactionservice.model.Credit,creditcard:com.bank.transactionservice.model.CreditCard 
      spring.json.trusted.packages: "*"
      heartbeat.interval.ms: 3000
      session.timeout.ms: 10000
      max.poll.interval.ms: 300000
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 10000
account-service:
 base-url: http://localhost:8082/api/accounts
credit-service:
 base-url-credit: http://localhost:8083/api
springdoc:
 api-docs:
   enabled: true
   path: /v3/api-docs
 swagger-ui:
   path: /swagger-ui.html
   operationsSorter: method
   tagsSorter: alpha
   docExpansion: none
management:
 endpoints:
   web:
     exposure:
       include: health, info, metrics, env
 endpoint:
   health:
     show-details: always
