server:
    port: 80
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server-cxgjf0gxbhbsfccz.canadacentral-01.azurewebsites.net/eureka
spring:
    application:
        name: yanki-service
    data:
        mongodb:
            uri: mongodb+srv://jeremy:Hola1234@bank-db.mongocluster.cosmos.azure.com/bank-db?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
        redis:
            host: redis-bootcamp.redis.cache.windows.net
            port: 6380
            password: ySxGplL2IJg6maslG3CUqZFemQjgkJOxkAzCaMBUle0=
            ssl: true
            timeout: 10000
    kafka:
        bootstrap-servers: bankkafka.servicebus.windows.net:9093
        properties:
            security:
                protocol: SASL_SSL
            sasl:
                mechanism: PLAIN
            sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="\$\ConnectionString" password="Endpoint=sb://bankkafka.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tVQTP6WHDJNy08SKfHu1t9qrz486rolhD+AEhJM5Ohk=";
        consumer:
            group-id: yanki-service-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: latest
            properties:
                spring.json.type.mapping: yankicardconfirmed:com.bank.yankiservice.dto.cardlink.CardLinkConfirmedEvent,yankicardrejected:com.bank.yankiservice.dto.cardlink.CardLinkRejectedEvent,yankitransactionprocessed:com.bank.yankiservice.dto.transaction.YankiTransactionProcessedEvent,balanceupdate:com.bank.yankiservice.dto.balance.BalanceUpdatedEvent
                spring.json.trusted.packages: "*"
                heartbeat.interval.ms: 3000
                session.timeout.ms: 10000
                max.poll.interval.ms: 300000
                reconnect.backoff.ms: 1000
                reconnect.backoff.max.ms: 10000
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: yankicardrequest:com.bank.yankiservice.dto.cardlink.CardLinkRequestedEvent,yankitransactionevent:com.bank.yankiservice.dto.transaction.YankiTransactionEvent
                spring.json.trusted.packages: "*"
springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
        tagsSorter: alpha
        docExpansion: none
management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, env
    endpoint:
        health:
            show-details: always
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 10
                failureRateThreshold: 50
                waitDurationInOpenState: 10s
                permittedNumberOfCallsInHalfOpenState: 3
                slowCallDurationThreshold: 5s
                slowCallRateThreshold: 50
jwt:
 secret: E{y(/so(hsqz`ngQW"C1`Lo#+kVq>q#P
 expiration: 86400000
